# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: IdiomsDB

on:
  push:
    branches:
        - 'develop'
        - 'main'
        - 'feature/**'
        - 'bugfix/**'
        - 'hotfix/**'
        - 'release/**'

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create SQLite database
      shell: bash
      run: |
        chmod +x scripts/create-db.sh
        scripts/create-db.sh
    - name: Test with pytest
      run: |
        pytest
